version: '3.8'
services:
  online-course:
    image: react-online-course
    container_name: react-online-course_c
    build: ./online-course/
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - 'courses'
    volumes:
      - ./online-course/:/app
      - ./app/node_modules

networks:
  - 'courses'
